import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../db/pool.js';

const page=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(8)});
const license=z.object({licenseNumber:z.string().min(1).max(120),dependency:z.enum(['تابع','غير تابع']).default('غير تابع'),department:z.string().max(200).optional(),internalStatus:z.string().max(120).optional(),closureRequestStatus:z.string().max(120).optional(),contractor:z.string().max(300).optional(),ownerEntity:z.string().max(300).optional(),consultant:z.string().max(300).optional(),roadName:z.string().max(300).optional(),latitude:z.number().finite().optional(),longitude:z.number().finite().optional(),processingDeadline:z.string().datetime().optional(),rawData:z.record(z.unknown()).default({})});
const collectorRows=z.object({rows:z.array(license).min(1).max(1000)});

export async function developedLicenseRoutes(app:FastifyInstance){
 app.get('/summary',async()=>{const {rows}=await pool.query(`SELECT count(*)::int total, count(*) FILTER (WHERE internal_status='مغلق أوليًا')::int initially_closed, count(*) FILTER (WHERE internal_status='مغلق')::int closed, count(*) FILTER (WHERE internal_status='تحت الإجراء')::int pending FROM developed_licenses WHERE dependency='تابع'`);return rows[0]});
 app.get('/licenses',async request=>{const q=request.query as Record<string,unknown>,p=page.parse(q),where:string[]=[`dependency='تابع'`],values:unknown[]=[];for(const [key,column] of [['search','license_number'],['department','department'],['internalStatus','internal_status'],['closureRequestStatus','closure_request_status']] as const){if(q[key]){values.push(key==='search'?`%${q[key]}%`:q[key]);where.push(key==='search'?`${column} ILIKE $${values.length}`:`${column}=$${values.length}`)}}values.push(p.pageSize,(p.page-1)*p.pageSize);const result=await pool.query(`SELECT id,license_number,department,internal_status,closure_request_status,contractor,owner_entity,processing_deadline,return_count,updated_at FROM developed_licenses WHERE ${where.join(' AND ')} ORDER BY updated_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);return {page:p.page,pageSize:p.pageSize,rows:result.rows}});
 app.get('/facets',async()=>{const {rows}=await pool.query(`SELECT department,count(*)::int count FROM developed_licenses WHERE dependency='تابع' GROUP BY department ORDER BY count DESC LIMIT 50`);return {departments:rows}});
 app.post('/upload',async request=>upsert((z.object({rows:z.array(license).min(1).max(5000)}).parse(request.body)).rows,'upload'));
 app.post('/collector-jobs',async()=>{const {rows}=await pool.query(`INSERT INTO developed_license_collector_jobs(status) VALUES('waiting_for_login') RETURNING *`);return rows[0]});
 app.get('/collector-jobs/:id',async request=>{const {rows}=await pool.query(`SELECT * FROM developed_license_collector_jobs WHERE id=$1`,[(request.params as {id:string}).id]);if(!rows[0])throw Object.assign(Error('Collector job غير موجود'),{statusCode:404});return rows[0]});
 app.post('/collector-jobs/:id/heartbeat',async request=>jobUpdate((request.params as {id:string}).id,'collecting'));
 app.post('/collector-jobs/:id/pause',async request=>jobUpdate((request.params as {id:string}).id,'paused'));
 app.post('/collector-jobs/:id/resume',async request=>jobUpdate((request.params as {id:string}).id,'collecting'));
 app.post('/collector-jobs/:id/complete',async request=>jobUpdate((request.params as {id:string}).id,'completed'));
 app.post('/collector-jobs/:id/fail',async request=>jobUpdate((request.params as {id:string}).id,'failed'));
 app.post('/collector-jobs/:id/records',async request=>{const body=collectorRows.parse(request.body);const out=await upsert(body.rows,'collector');await pool.query(`UPDATE developed_license_collector_jobs SET received_rows=received_rows+$2,status='collecting',last_heartbeat_at=now(),updated_at=now() WHERE id=$1`,[(request.params as {id:string}).id,body.rows.length]);return out});
 app.patch('/:id/classification',async request=>{const id=z.coerce.number().int().positive().parse((request.params as {id:string}).id),body=z.object({dependency:z.enum(['تابع','غير تابع']),department:z.string().max(200).optional(),actor:z.string().max(150).default('system')}).parse(request.body);const {rows}=await pool.query(`UPDATE developed_licenses SET dependency=$2,department=$3,manual_classification=true,updated_at=now() WHERE id=$1 RETURNING *`,[id,body.dependency,body.department||null]);if(!rows[0])throw Object.assign(Error('الرخصة غير موجودة'),{statusCode:404});await pool.query(`INSERT INTO developed_license_status_history(license_id,reason,changed_by) VALUES($1,'manual classification',$2)`,[id,body.actor]);return rows[0]});
 app.get('/closure-queue',async()=>{const {rows}=await pool.query(`SELECT *, EXTRACT(day FROM processing_deadline-now())::int remaining_days FROM developed_licenses WHERE dependency='تابع' AND closure_request_status NOT IN ('مغلق','مغلق أوليًا') ORDER BY processing_deadline NULLS LAST LIMIT 500`);return {rows}});
 app.get('/map',async request=>{const q=request.query as Record<string,unknown>,box=String(q.bbox||'').split(',').map(Number);if(box.length!==4||box.some(x=>!Number.isFinite(x)))throw Object.assign(Error('bbox غير صالح'),{statusCode:400});const {rows}=await pool.query(`SELECT id,license_number,latitude,longitude,internal_status FROM developed_licenses WHERE dependency='تابع' AND longitude BETWEEN $1 AND $3 AND latitude BETWEEN $2 AND $4 LIMIT 2000`,box);return {type:'FeatureCollection',features:rows.map(r=>({type:'Feature',geometry:{type:'Point',coordinates:[Number(r.longitude),Number(r.latitude)]},properties:r}))}});
 app.post('/sync',async()=>{const {rows}=await pool.query(`INSERT INTO developed_license_sync_runs(direction,status,completed_at,detail) VALUES('developed-to-current','queued',now(),'{}') RETURNING *`);return rows[0]});
}
async function jobUpdate(id:string,status:string){const {rows}=await pool.query(`UPDATE developed_license_collector_jobs SET status=$2,last_heartbeat_at=now(),updated_at=now() WHERE id=$1 RETURNING *`,[id,status]);if(!rows[0])throw Object.assign(Error('Collector job غير موجود'),{statusCode:404});return rows[0]}
async function upsert(rows:z.infer<typeof license>[],source:string){const client=await pool.connect();try{await client.query('BEGIN');let dependent=0;for(const row of rows){const sourceResult=await client.query(`INSERT INTO developed_license_source(license_number,source_name,raw_data,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(license_number,source_name) DO UPDATE SET raw_data=EXCLUDED.raw_data,updated_at=now() RETURNING id`,[row.licenseNumber,source,row.rawData]);if(row.dependency==='تابع'){dependent++;await client.query(`INSERT INTO developed_licenses(license_number,source_id,dependency,department,internal_status,closure_request_status,contractor,owner_entity,consultant,road_name,latitude,longitude,processing_deadline,raw_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(license_number) DO UPDATE SET source_id=EXCLUDED.source_id,dependency=CASE WHEN developed_licenses.manual_classification THEN developed_licenses.dependency ELSE EXCLUDED.dependency END,department=CASE WHEN developed_licenses.manual_classification THEN developed_licenses.department ELSE EXCLUDED.department END,internal_status=COALESCE(EXCLUDED.internal_status,developed_licenses.internal_status),closure_request_status=COALESCE(EXCLUDED.closure_request_status,developed_licenses.closure_request_status),updated_at=now()`,[row.licenseNumber,sourceResult.rows[0].id,row.dependency,row.department||null,row.internalStatus||'تحت الإجراء',row.closureRequestStatus||'غير مقدم',row.contractor||null,row.ownerEntity||null,row.consultant||null,row.roadName||null,row.latitude||null,row.longitude||null,row.processingDeadline||null,row.rawData])}}await client.query('COMMIT');return {received:rows.length,storedDependent:dependent}}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
