import { createReadStream } from 'node:fs';
import { parse } from 'csv-parse';
import { pool } from './db/pool.js';

const path=process.argv[2];if(!path)throw Error('الاستخدام: npm run import:csv -- /path/licenses.csv');
const clean=(v:unknown)=>String(v??'').trim().replace(/\s+/g,' '),digits=(v:unknown)=>clean(v).replace(/\D/g,'');
const pick=(row:Record<string,string>,...keys:string[])=>{const map=new Map(Object.entries(row).map(([k,v])=>[clean(k).replace(/[أإآ]/g,'ا'),v]));for(const key of keys){const value=map.get(clean(key).replace(/[أإآ]/g,'ا'));if(value!==undefined)return clean(value)}return''};
type Row={licenseNumber:string;closureNumber:string;contractor:string;consultant:string;projectName:string;roadName:string;district:string;supervisingEntity:string;dependency:string;department:string;status:string;latitude:number|null;longitude:number|null;raw:Record<string,string>};
const batch:Row[]=[];let processed=0;
async function flush(){if(!batch.length)return;const columns=14,params:unknown[]=[],values=batch.map((row,index)=>{const start=index*columns;params.push(row.licenseNumber,row.closureNumber||null,row.contractor||null,row.consultant||null,row.projectName||null,row.roadName||null,row.district||null,row.supervisingEntity||null,row.dependency,row.department,row.status,row.latitude,row.longitude,JSON.stringify(row.raw));return`(${Array.from({length:columns},(_,i)=>`$${start+i+1}`).join(',')})`}).join(',');await pool.query(`INSERT INTO licenses(license_number,closure_number,contractor,consultant,project_name,road_name,district,supervising_entity,dependency,department,analysis_status,latitude,longitude,raw_data) VALUES ${values} ON CONFLICT(license_number) DO UPDATE SET closure_number=EXCLUDED.closure_number,contractor=EXCLUDED.contractor,consultant=EXCLUDED.consultant,project_name=EXCLUDED.project_name,road_name=EXCLUDED.road_name,district=EXCLUDED.district,supervising_entity=EXCLUDED.supervising_entity,dependency=EXCLUDED.dependency,department=EXCLUDED.department,analysis_status=EXCLUDED.analysis_status,latitude=EXCLUDED.latitude,longitude=EXCLUDED.longitude,raw_data=EXCLUDED.raw_data,updated_at=NOW()`,params);processed+=batch.length;batch.length=0;if(processed%10000===0)console.log(`Imported ${processed.toLocaleString()} rows`)}
const parser=createReadStream(path).pipe(parse({columns:true,bom:true,skip_empty_lines:true,relax_column_count:true,trim:true}));
for await(const raw of parser){const row=raw as Record<string,string>,licenseNumber=digits(pick(row,'رقم الرخصة','رقم الترخيص','license number','license_no'));if(!licenseNumber)continue;const dependency=pick(row,'التبعية')==='تابع'?'تابع':'غير تابع',lat=Number(pick(row,'خط العرض','Latitude','Lat')),lng=Number(pick(row,'خط الطول','Longitude','Lon','Long'));batch.push({licenseNumber,closureNumber:pick(row,'رقم الإغلاق','رقم الاغلاق','closure number'),contractor:pick(row,'اسم المقاول','المقاول','contractor'),consultant:pick(row,'اسم الاستشاري','الاستشاري'),projectName:pick(row,'اسم المشروع','المشروع'),roadName:pick(row,'اسم الشارع','اسم الطريق','الشارع','الطريق'),district:pick(row,'الحي'),supervisingEntity:pick(row,'اسم الجهة المشرفة','الجهة المشرفة','الجهة المالكة'),dependency,department:pick(row,'الإدارة','الادارة')||'رخص خارج نطاق الوكالة',status:pick(row,'الحالة','حالة التحليل')||'تحت الإجراء',latitude:Number.isFinite(lat)?lat:null,longitude:Number.isFinite(lng)?lng:null,raw:row});if(batch.length>=1000)await flush()}
await flush();await pool.query('REFRESH MATERIALIZED VIEW CONCURRENTLY license_daily_metrics');await pool.query('REFRESH MATERIALIZED VIEW CONCURRENTLY license_global_facets');await pool.end();console.log(`Completed: ${processed.toLocaleString()} licenses`);
